"""add unique constraint portfolio coin

Revision ID: 6cf8e9d4780d
Revises: 797902e9c67f
Create Date: 2025-07-11 01:29:32.782361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf8e9d4780d'
down_revision: Union[str, Sequence[str], None] = '797902e9c67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_portfolio_id_coin_id', 'portfolio_coins', ['portfolio_id', 'coin_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_portfolio_id_coin_id', 'portfolio_coins', type_='unique')
    # ### end Alembic commands ###
