services:
  db:
    image: postgres:16
    container_name: postgres-p
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db:
    driver: local
